derpfest: add brazilian portuguese translation
DerpLab/platform_packages_apps_ThemePicker pull request #2
Opened 2020-03-15 03:31 UTC by jeangraff30

2020-03-15 03:33 UTC, jeangraff30 commented
From what I see I didn't have the values-pt-rBR folder, so I checked the other folders, and I believe this folder is right

2020-03-15 08:45 UTC, poad42 commented
Might wanna edit those copyright headers

2020-03-16 14:02 UTC, idoybh commented
> Might wanna edit those copyright headers

True

2020-03-16 14:06 UTC, idoybh requested changes

2020-03-16 14:06 UTC, idoybh commented on res/values-pt/aosip_strings.xml
> +     Copyright (C) 2020 The PixelDust Project
```suggestion
     Copyright (C) 2020 DerpFest
```

2020-03-16 14:07 UTC, idoybh approved these changes

2020-03-16 14:35 UTC, idoybh approved these changes

2020-03-16 14:37 UTC, merged